services:
  mariadb:
    image: mariadb:lts-ubi
    restart: always
    container_name: mariadb 
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    volumes:
      - my_data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  my_data: